//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Answer
    {
        public int id { get; set; }
        public int id_SubQuestion { get; set; }
        public string answerContent { get; set; }
        public bool isCorrect { get; set; }
        public int Ordering { get; set; }
    
        public virtual tb_SubQuestion tb_SubQuestion { get; set; }
    }
}
