//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_QuizDetail
    {
        public int id { get; set; }
        public Nullable<int> id_Quiz { get; set; }
        public Nullable<int> id_SubQuestion { get; set; }
        public Nullable<int> C_order { get; set; }
        public Nullable<int> id_AnswerMember { get; set; }
    
        public virtual tb_Quiz tb_Quiz { get; set; }
        public virtual tb_SubQuestion tb_SubQuestion { get; set; }
    }
}
