//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_QuangCao
    {
        public int id { get; set; }
        public Nullable<int> id_ViTri { get; set; }
        public string linkHinhAnh { get; set; }
        public string linkWeb { get; set; }
    
        public virtual tb_ViTriQC tb_ViTriQC { get; set; }
    }
}
